version: 2.1

# orbs:
#   vercel: vercel@latest

jobs:
  build:
    docker:
      - image: circleci/node:16
    # environment:
    #   VERCEL_PROJECT_ID: prj_sAbgfGT8IZyCfvlKpQikbouARMlv
    #   VERCEL_ORG_ID: 
    steps:
      - checkout
      - run:
          name: Install Vercel CLI
          command: sudo npm install --global vercel@latest
      # - run:
      #     name: Install Vercel CLI
      #     command: |
      #       curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
      #       export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
      #       yarn global add vercel
      - run:
          name: Deploy to Vercel
          command: |
            # vercel --token $VERCEL_TOKEN --prod
            vercel --token "Q42grJbnfYvQQcIxkl41G4zQ" --prod --confirm


workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global